### ISSUE TITLE
[BUG] hotpot daemon make fails on FreeBSD

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/opensds-formula#111]
### Pillar / config used

---

### Describe the bug

```
          ID: opensds hotpot daemon opensds software build make
    Function: cmd.run
        Name: make
      Result: False
     Comment: Attempt 1: Returned a result of "False", with the following comment: "Command "make" run"
              Attempt 2: Returned a result of "False", with the following comment: "Command "make" run"
              Command "make" run
     Started: 02:58:35.651361
    Duration: 128082.605 ms
     Changes:
              ----------
              pid:
                  32580
              retcode:
                  1
              stderr:
                  make: exec(go) failed (No such file or directory)
              stdout:
                  mkdir -p /build/out
                  go build -o /build/out/bin/osdsdock github.com/opensds/opensds/cmd/osdsdock
                  *** Error code 1

                  Stop.
                  make: stopped in /usr/local/golang/packages/src/github.com/opensds/opensds
```

**Comment by noelmcloughlin** [comment]
And systemctl is not available on FreeBSD.
```
          ID: opensds hotpot daemon opensds systemd started
    Function: cmd.run
        Name: systemctl daemon-reload
      Result: False
     Comment: Command "systemctl daemon-reload" run
     Started: 03:00:44.016101
    Duration: 17.164 ms
     Changes:
              ----------
              pid:
                  32586
              retcode:
                  127
              stderr:
                  /usr/local/bin/bash: systemctl: command not found
              stdout:
----------
          ID: opensds hotpot daemon opensds systemd started
    Function: service.running
        Name: opensds-opensds
      Result: False
     Comment: One or more requisite failed: opensds.hotpot.daemon.opensds hotpot daemon opensds systemd started
```

**Comment by noelmcloughlin** [comment]
```
          ID: opensds dock daemon osdsdock systemd started
    Function: cmd.run
        Name: systemctl daemon-reload
      Result: False
     Comment: Command "systemctl daemon-reload" run
     Started: 03:01:18.612508
    Duration: 16.026 ms
     Changes:
              ----------
              pid:
                  32965
              retcode:
                  127
              stderr:
                  /usr/local/bin/bash: systemctl: command not found
```
