### ISSUE TITLE
[centos] multi-cloud systemd service fails

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/opensds-formula#37]
This was initial deployment of OpenSDS on CentOS7
```
----------
          ID: opensds gelato daemon systemd multi-cloud service started
    Function: service.running
        Name: opensds-multi-cloud
      Result: False
     Comment: Service opensds-multi-cloud has been enabled, and is dead
     Started: 17:40:58.915387
    Duration: 297.844 ms
     Changes:   
              ----------
              opensds-multi-cloud:
                  True
```
Logs
```
[root@localhost multi-cloud]# docker-compose up -d
Creating network "multicloud_default" with the default driver
ERROR: Failed to program FILTER chain: iptables failed: iptables --wait -I FORWARD 
-o br-0a7584956716 -j DOCKER: iptables v1.4.21: 
Couldn't load target `DOCKER':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2)
```
