### ISSUE TITLE
[centos] [dashboard] wrong osfamilymap nginx path

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/opensds-formula#38]
Looks like nginx path is wrong in `osfamilymap.yaml` for CentOS
```
----------
          ID: opensds dashboard container dashboard running
    Function: docker_container.running
        Name: dashboard
      Result: False
     Comment: Created container 'dashboard'. Failed to start container 'dashboard': 'Error 400: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/nginx/sites-available/default\\\" to rootfs \\\"/var/lib/docker/overlay2/f42989007c5b2b2a27ebc025f570fd6669287a868ead1a5867f5a46b6b766aa6/merged\\\" at \\\"/var/lib/docker/overlay2/f42989007c5b2b2a27ebc025f570fd6669287a868ead1a5867f5a46b6b766aa6/merged/etc/nginx/sites-available/default\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type'.
     Started: 17:31:12.546618
    Duration: 437409.91 ms
     Changes:   
              ----------
              container_id:
                  ----------
                  added:
                      c66ed18ece2ef754c0edb9f74ed44b6636a7c1a0f44efa77daa4f945fdb1706b
              image:
                  ----------
                  Layers:
                      ----------
                      Pulled:
                          - b775667b1fd0
                          - 4b105072aa89
                          - 83ef5c84ec9c
                          - f567c7054a96
                          - 0fe156bcb4b1
                          - 07fa96bb7d5e
                          - 4dd021921c9a
                          - 42dae22f8cd7
                          - e1a8721afe6e
                          - f77ff8405034
                          - 099ee7dd0a81
                          - fb9906355a0f
                          - 3fbdf05660f5
                  Status:
                      Downloaded newer image for opensdsio/dashboard:bali
                  Time_Elapsed:
                      2.55150794983
                  retcode:
                      0
```
