### ISSUE TITLE
Make cinder blockbox fails on CentOS. 

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/opensds-formula#68]
Needs to be customized for CentOS
```
          ID: opensds backend block daemon cinder software build make blockbox
    Function: cmd.run
        Name: make blockbox
      Result: False
     Comment: Command "make blockbox" run
     Started: 03:14:00.080141
    Duration: 3173.534 ms
     Changes:
              ----------
              pid:
                  24647
              retcode:
                  2
              stderr:
                  unable to prepare context: unable to 'git clone' to temporary context directory: error initializing submodules: usage: git submodule [--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <repository>] [--] <repository> [<path>]
                     or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
                     or: git submodule [--quiet] init [--] [<path>...]
                     or: git submodule [--quiet] deinit [-f|--force] [--] <path>...
                     or: git submodule [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
                     or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
                     or: git submodule [--quiet] foreach [--recursive] <command>
                     or: git submodule [--quiet] sync [--recursive] [--] [<path>...]
                  : exit status 1
                  make: *** [base] Error 1
              stdout:
                  docker build https://git.openstack.org/openstack/loci.git \
                        --build-arg PROJECT=cinder \
                        --build-arg FROM=debian:stretch \
                        --build-arg PROJECT_REF=master \
                        --tag debian-cinder:latest
```
