### ISSUE TITLE
Failed to start container 'dashboard' on Suse

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/opensds-formula#77]
```
          ID: opensds dashboard daemon dashboard container running
    Function: docker_container.running
        Name: dashboard
      Result: False
     Comment: Created container 'dashboard'. Failed to start container 'dashboard': 'Error 400: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/nginx/sites-available/default\\\" to rootfs \\\"/var/lib/docker/btrfs/subvolumes/cf8113a0f42659e88bfda8ad2ca647d1152249b98b310e9561a8c0e83750eafb\\\" at \\\"/var/lib/docker/btrfs/subvolumes/cf8113a0f42659e88bfda8ad2ca647d1152249b98b310e9561a8c0e83750eafb/etc/nginx/conf.d/default.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type'.
     Started: 10:34:05.299510
    Duration: 31699.527 ms
     Changes:
              ----------
              container_id:
                  ----------
                  added:
                      db64a3caa3805bc57e68d77abe7d8a94878e2e5d240e7043011222babdbb2a25
              image:
                  ----------
                  Layers:
                      ----------
                      Pulled:
                          - f789259667da
                          - cd784148e348
                          - 7e5cdc0df0c4
                          - 44249028334b
                          - 7c0ea5070fa4
                          - 437435d1a872
                          - 9f5a4538dd6e
                          - 2b554a36c05f
                  Status:
                      Downloaded newer image for opensdsio/dashboard:latest
                  Time_Elapsed:
                      2.373220920562744
                  retcode:
                      0
```
